version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8090:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: "db"
    image: "postgres:15.1"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres